export const grainsProteinData = {
  "Rastrojo/Paja": 3,
  "Heno Alfallfa": 17,
  "Heno Avena": 10,
  "Ensilado Maiz": 8,
  "Pradera Templada": 15,
  "Pradera Tropical": 9,
  "Masilla Cerveceria": 27,
  "Subproducto Panaderia": 10,
  "Canola": 40,
  "Pasta Coco": 21,
  "Maiz Grano": 9,
  "Olote de Maiz": 3,
  "Gluten de Maiz 41% PC": 46,
  "Glulten de Maiz 60% PC": 67,
  "Harinolina 41% PC": 48,
  "Harina Pescado": 66,
  "Harina Carne Cerdo/Pollo": 56,
  "Melaza Caña": 6,
  "Pasta Girasol": 38,
  "Sorgo Grano": 11,
  "Pasta de Soya 44% PC": 49,
  "Cascarilla de Soya": 13,
  "Triticale Grano": 14,
  "Trigo Grano": 14,
  "Salvado de Trigo": 17,
  "Pollinaza": 28,
}