export const grainsProteinData = [
  { name: "Rastrojo/Paja", value: 3 },
  { name: "Heno Alfallfa", value: 17 },
  { name: "Heno Avena", value: 10 },
  { name: "Ensilado Maiz", value: 8 },
  { name: "Pradera Templada", value: 15 },
  { name: "Pradera Tropical", value: 9 },
  { name: "Masilla Cerveceria", value: 27 },
  { name: "Subproducto Panaderia", value: 10 },
  { name: "Canola", value: 40 },
  { name: "Pasta Coco", value: 21 },
  { name: "Maiz Grano", value: 9 },
  { name: "Olote de Maiz", value: 3 },
  { name: "Gluten de Maiz 41% PC", value: 46 },
  { name: "Glulten de Maiz 60% PC", value: 67 },
  { name: "Harinolina 41% PC", value: 48 },
  { name: "Harina Pescado", value: 66 },
  { name: "Harina Carne Cerdo/Pollo", value: 56 },
  { name: "Melaza Caña", value: 6 },
  { name: "Pasta Girasol", value: 38 },
  { name: "Sorgo Grano", value: 11 },
  { name: "Pasta de Soya 44% PC", value: 49 },
  { name: "Cascarilla de Soya", value: 13 },
  { name: "Triticale Grano", value: 14 },
  { name: "Trigo Grano", value: 14 },
  { name: "Salvado de Trigo", value: 17 },
  { name: "Pollinaza", value: 28 },
]